### PR TITLE
Composition vs inheritance

### PR DESCRIPTION
**Pull request by GCrispino**
References #25.

I believe the translation is fair. I just have some questions:
- I treated props as a feminine gender noun. I don't know if this is right, but that made sense to me.
- Also, I took the liberty to translate some component names and create new CodePens to show them. Components like `<Dialog />` were left untranslated but `<WelcomeDialog />`, for example, was translated to `<DialogBenvenuti />`. I'm open to suggestions, though, if you think this is not right.

### CODE REVIEW

**Comment by GCrispino** [comment]
@deblasis No worries! I know that my Italian has a lot to improve, and if you think that it's better for a native speaker to do it rather than me, that's no problem 😃. 
While I wait for your reviews, I'll start to fix the other points that you mentioned.

Thank you!

**Comment by deblasis** [comment]
Hi @GCrispino, so... I had a look at your translation, started reviewing it but I gave up after noticing that I was rewriting it 😞, please have a look at the first suggestions to have an idea. I really appreciate your attempt but I would abandon this PR and make the page available for other translators, if @LucaBlackDragon agrees with me of course. Sorry for not getting back to you earlier, I hope you didn't spend more time on this meanwhile. 
Ciao! 😄

**Comment by GCrispino** [comment]
@deblasis no problem! Thank you so much for your feedback, and sorry to waste your time.

**Comment by deblasis** [comment]
No worries @GCrispino, thanks anyways!

**Comment by LucaBlackDragon** [comment]
I'm sorry to reply so late, this is going to be a busy week for me. I'll try to focus on reviewing PRs... Anyway I agree with @deblasis, but thanks again for the effort @GCrispino!

**Pull request closed without merging**
